### ISSUE TITLE
Mica.starcheck fails in Ska3 (no asciitable)

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#104]
This would indicate there is inadequate test coverage and/or tests weren't run on Py3.

**Comment by jeanconn** [comment]
Tests weren't run on Py3.  This code has not had Py3 conversion attention yet, and that wasn't on top of my list for #98.  I had a separate branch open working the Py3 fixes and updating tests.

**Comment by jeanconn** [comment]
Closed by #105
