### ISSUE TITLE
Make a table / database of acq anomalies

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#158]
From:
https://github.com/sot/mica/pull/144#issuecomment-331965164

The numbers below should be stored somewhere that is easy to get:
```
Acquisition Anomaly.  Star for slot 1 actually in box 6
Large Deviation from Expected ACQ Star Position in 20795
      Slot 1 Expected (Y-Pos, Z-Pos) = (571.0, 1687.0)
      Slot 1 Observed (Y-Pos, Z-Pos) = (-688.4, -1062.8)
      Halfwidth 120        (dy, dz) = (-1259.3, -2749.8)
```
For now searching on email alerts is probably good enough.

**Comment by jeanconn** [comment]
We're probably OK with https://cxc.cfa.harvard.edu/mta/ASPECT/wrong_box_anom/ for now and could also put out a data file from that if needed.
