### ISSUE TITLE
starcheck_parser is now in starcheck

### ISSUE THREAD

**Issue by jeanconn** [sot/mica#204]
Since starcheck parser got moved into starcheck, it looks like proseco's get_kwargs_from_starcheck_text and some annie test pieces that want mica.starcheck.starcheck_parser are going to be broken on systems without starcheck.    

That's not a problem in envs with starcheck/perl/production envs, but might be undesireable overall.

**Comment by taldcroft** [comment]
Can we just add the `starcheck` package to `ska3-flight` and `ska3-matlab`?

**Comment by jeanconn** [comment]
Do you mean build the starcheck conda package without the dependencies
called out (like Perl that isn't built on 32 bit)?  I'm not thrilled with
that.

**Comment by taldcroft** [comment]
I didn't realize (or forgot) the starcheck `pip install ..` in `build.py` is actually installing all the Perl source.   Anyway we can find a way to finesse this.

**Comment by jeanconn** [comment]
I like that the conda install of starcheck does try to get the deps to give the user a working version of starcheck, but it wouldn't be in the end of the world if the install just installed the starcheck pieces and one would need to install ska3-perl to have the rest of the Perl packages necessary to run starcheck.  ska3-perl does have other pieces that aren't required to run starcheck though (and if we'd want to capture the dependencies someplace else we'd need something else to do that).

**Comment by taldcroft** [comment]
Maybe remove `scripts=['starcheck/src/starcheck']` from setup.py and then install only that launcher script (and require the perl deps) as a separate package `starcheck-perl` or somesuch.

**Comment by jeanconn** [comment]
So, your thought is two conda recipes to tease this apart along with two install paths to follow in the setup.py in the single starcheck repo?

I was leaning toward letting starcheck install without deps but update the `starcheck/src/starcheck` script so it has a useful error if installed without ska3-perl.

**Comment by taldcroft** [comment]
> I was leaning toward letting starcheck install without deps but update the starcheck/src/starcheck script so it has a useful error if installed without ska3-perl.

That also sounds fine to me.

**Comment by taldcroft** [comment]
For the record this issue does cause three proseco test fails in current ska3-flight without starcheck installed.
