### ISSUE TITLE
Exclude star 613557312

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#209]
In SEP2319/oflsa/starcheck.html#obsid47858.  This has failed 3/3 for acq, 2/2 for guide due to mag=5.5.

**Comment by jeanconn** [comment]
When do you want to just redefine the rules and do a programmatic update to the list?

**Comment by taldcroft** [comment]
As soon as one of us finds time to write the code.

**Comment by taldcroft** [comment]
And do the thinking to decide what the rules are..

**Comment by taldcroft** [comment]
Bad star added to the AGASC supplement.
