### ISSUE TITLE
Add guide star 5th, 16th, 50th, 84th, and 95th percentile mag columns to guide stats. 

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#216]
Let's just do this now and start reprocessing the mission for https://github.com/sot/ska-projects/issues/114.

**Comment by taldcroft** [comment]
BTW this processing is likely completely I/O bound and I would imagine it might run an order of magnitude faster on a local laptop with SSD.  Since it would be nice to have agile repro capability, might be worth the time to see if this can run on a laptop.

**Comment by taldcroft** [comment]
With the idea the @javierggt could actually run it once @jeanconn makes it work (if it does not already).

**Comment by jeanconn** [comment]
Great idea!

**Comment by jeanconn** [comment]
Oh question though, this time around what do we want our mag convention to be for no data?  Every time I mask something I break all your speedy stuff.

**Comment by taldcroft** [comment]
Call it 99.0 mag.  And yes, masked arrays can be more trouble than they're worth.
