### ISSUE TITLE
Add a new data table to agasc_supplement called `mags`

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#217]
Add a new top-level data table called `mags` (analogous to current `bads`) which has three columns:
- agasc_id
- mag_aca
- mag_aca_err

This will be populated by a TBD mechanism based on the guide_stats database.  The plan is for incremental improvements in algorithm, starting with something simple and gaining sophistication with time and understanding.  We can also add columns as we find them necessary in practice.

At a minimum this will have data for all observed stars where the observed magnitude differs "substantially" from the catalog magnitude.  Substantially could initially mean that `mag_aca` here is more than 1-sigma from the catalog mag.

The intent is for this table to be small to reduce the performance impact in proseco.  However once we have an implementation we can profile and see.

**Comment by jeanconn** [comment]
No longer a mica issue.
