### ISSUE TITLE
Add functionality for dark_cal.py

### ISSUE THREAD

**Issue by taldcroft** [sot/mica#26]
Use `dark_cals_with_temp.py` as a rough starting point to do automated processing related to ACA dark cals.  Define archive directory structure:

```
/data/aca/archive/aca_dark/{YYYYDDD}/
  dark_image.fits
  properties.json
```

This will copy the final `imd.fits` in `$SKA/analysis/aca_dark_cal` and put relevant information into `properties.json`.

@jeanconn - I'm assigning myself.  If you've thought about this at all and have some ideas for content / organization please add them here.

**Comment by jeanconn** [comment]
I think this is done.
